
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 28 02:52:29 CEST 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 33;
  public static final int CHAR = 50;
  public static final int CONST = 6;
  public static final int NOTEQUAL = 23;
  public static final int LPAREN = 42;
  public static final int SEMI = 35;
  public static final int CONTINUE = 15;
  public static final int LESS = 24;
  public static final int FOR = 13;
  public static final int MINUS = 18;
  public static final int RPAREN = 43;
  public static final int STATIC = 16;
  public static final int OROR = 45;
  public static final int AND = 26;
  public static final int OR = 27;
  public static final int BOOL = 49;
  public static final int COMMA = 36;
  public static final int CLASS = 4;
  public static final int EQUALEQUAL = 22;
  public static final int ANDAND = 44;
  public static final int SQUAREBRACKETLEFT = 38;
  public static final int DIV = 20;
  public static final int DIVEQUAL = 31;
  public static final int MOREOREQUAL = 46;
  public static final int LESSOREQUAL = 25;
  public static final int PLUS = 17;
  public static final int IF = 7;
  public static final int DOT = 37;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 34;
  public static final int RETURN = 11;
  public static final int EQUAL = 28;
  public static final int SQUAREBRACKETRIGHT = 39;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int MUL = 19;
  public static final int NUMBER = 51;
  public static final int PLUSEQUAL = 29;
  public static final int MOD = 21;
  public static final int IDENT = 52;
  public static final int BREAK = 3;
  public static final int VOID = 12;
  public static final int LBRACE = 40;
  public static final int ELSE = 5;
  public static final int READ = 10;
  public static final int MINUSEQUAL = 30;
  public static final int RBRACE = 41;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int MODEQUAL = 32;
  public static final int MULEQUAL = 48;
  public static final int MORE = 47;
  public static final int PRINT = 9;
}

